master:
  node_id: 7
  sync_period: 2500 # [us]    for catheter CSTAR robot do not go below 1500[us]

slave_1:
  dcf: "Epos2.eds"
  node_id: 1
  revision_number: 0x21250000

slave_2:
  dcf: "Epos2.eds"
  node_id: 2
  # revision_number: 0x21250000
  revision_number: 0x21260000

slave_3:
  dcf: "Epos2.eds"
  node_id: 3
  # revision_number: 0x21260000
  revision_number: 0x21250000

slave_4:
  dcf: "Epos2.eds"
  node_id: 4
  revision_number: 0x21260000

slave_5:
  dcf: "Epos2.eds"
  node_id: 5
  revision_number: 0x21250000

slave_6:
  dcf: "Epos2.eds"
  node_id: 6
  revision_number: 0x21260000
  